config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # User management
    path("users/", include("zanhu01.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

zanhu01/users/urls.py
from django.urls import path
from zanhu01.users import views

app_name = "users"
urlpatterns = [
    path('update/', views.UserUpdateView.as_view(), name='update'),
    path('<username>/', views.UserDetailView.as_view(), name='detail'),
]

zanhu01/users/models.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# __author__ = '__Jack__'

from __future__ import unicode_literals
#为了让python2象3一样处理unicode字符
# from django.utils.encoding import python_2_unicode_compatible
from six import python_2_unicode_compatible
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


@python_2_unicode_compatible
class User(AbstractUser):
    """自定义用户模型"""
    nickname = models.CharField(null=True, blank=True, max_length=255, verbose_name='昵称')
    job_title = models.CharField(max_length=50, null=True, blank=True, verbose_name='职称')
    introduction = models.TextField(blank=True, null=True, verbose_name='简介')
    # upload_to要填路径
    picture = models.ImageField(upload_to='profile_pics/', null=True, blank=True, verbose_name='头像')
    location = models.CharField(max_length=50, null=True, blank=True, verbose_name='城市')
    personal_url = models.URLField(max_length=555, blank=True, null=True, verbose_name='个人链接')
    weibo = models.URLField(max_length=255, blank=True, null=True, verbose_name='微博链接')
    zhihu = models.URLField(max_length=255, blank=True, null=True, verbose_name='知乎链接')
    github = models.URLField(max_length=255, blank=True, null=True, verbose_name='Github链接')
    linkedin = models.URLField(max_length=255, blank=True, null=True, verbose_name='LinkedIn链接')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    # 设置元数据
    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
    # 模型类实例，直观可读的方法
    def __str__(self):
        return self.username
    # 返回用户详情页中url的路径，因为每个用户的详情页都是不一样的
    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})
    # 个人信息中返回用户的名字
    def get_profile_name(self):
        if self.nickname:
            return self.nickname
        return self.username

zanhu01/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):
    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }

zanhu01/users/views.py
#!/usr/bin/python3
# -*- coding:utf-8 -*-
# __author__ = '__Jack__'

from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, UpdateView

from zanhu01.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/user_detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'

class UserUpdateView(LoginRequiredMixin, UpdateView):
    """用户只能更新自己的信息"""
    fields = ['nickname', 'email', 'picture', 'introduction', 'job_title', 'location',
              'personal_url', 'weibo', 'zhihu', 'github', 'linkedin']
    model = User
    template_name = 'users/user_form.html'

    def get_success_url(self):
        """更新成功后跳转到用户自己页面"""
        return reverse('users:detail', kwargs={'username': self.request.user.username})

    def get_object(self, queryset=None):
        return self.request.user

zanhu01/templates/base.html
{% load static thumbnail compress cache %}<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}赞乎{% endblock title %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <meta name="description" content="赞乎问答社区">
    <meta name="author" content="__Sharon__">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% compress css %}
        <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Your stuff: Third-party CSS libraries go here -->
        <link rel="stylesheet" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <!-- This file stores project-specific CSS -->
        <link rel="stylesheet" href="{% static 'css/zanhu.css' %}">
        {% block css %}{% endblock css %}
    {% endcompress %}

</head>
<body>
{% cache 3600 sidebar request.user.username %}
    <nav class="navbar fixed-top navbar-expand-sm bg-light">
        <div class="container">
<!--            <a class="navbar-brand" href="#">赞 乎&nbsp;&nbsp;</a>-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mainMenu">

                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="btn-sm" href="#" id="notifications" data-toggle="popover"
                           data-title="通知">
                            <i class="fa fa-bell-o" aria-hidden="true"></i>
                        </a>
                    </li>
                </ul>&nbsp;&nbsp;

                <ul class="navbar-nav mr-auto">
<!--                    <li class="nav-item"><a class="nav-link" href="#">&nbsp;&nbsp;首页</a></li>&nbsp;&nbsp;-->
                    <li class="nav-item"><a class="nav-link" href="#">文章</a></li>&nbsp;&nbsp;
                    <li class="nav-item"><a class="nav-link" href="#">问答</a></li>&nbsp;&nbsp;
                    <li class="nav-item"><a class="nav-link" href="#">私信</a></li>&nbsp;&nbsp;
                </ul>

                <form role="search" action="#">
                    <div class="input-group">
                        <input name="q" type="search" id="searchInput" class="form-control" placeholder="搜索" aria-label="Search">
                        <div class="input-group-append">
                            <button class="input-group-text"><i class="fa fa-search" aria-hidden="true"></i></button>
                        </div>
                    </div>
                </form>
                {% if request.user.is_authenticated %}
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false">
                                {% thumbnail request.user.picture "x40" as im %}
                                    <img src="{{ im.url }}" style="border-radius: 50%;" alt="用户头像" class="user-image">
                                    {% empty %}
                                    <img src="{% static 'img/user.png' %}" height="40px" alt="没有头像"/>
                                {% endthumbnail %}
                                {{ request.user.username }}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'users:detail' request.user.username %}">
                                    <i class="fa fa-cogs fa-fw" aria-hidden="true"></i> 设置</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{% url 'account_logout' %}">
                                    <i class="fa fa-sign-out fa-fw" aria-hidden="true"></i> 退出</a>
                            </div>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </nav>
{% endcache %}
<div class="mb-3"></div>
<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div id="messages" class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}{% endblock content %}
</div>
<!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->

<!-- Required by Bootstrap v4 -->
{% compress js %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
    <!-- Your stuff: Third-party javascript libraries go here -->
    <script src="{% static 'js/jquery-ui.min.js' %}" type="text/javascript"></script>
    <!-- place project specific Javascript in this file -->
    <script type="text/javascript">
        const currentUser = "{{ request.user.username }}";
    </script>
    <script src="{% static 'js/reconnecting-websocket.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/notifications.js' %}" type="text/javascript"></script>
    {% block js %}{% endblock js %}
{% endcompress %}

</body>

<!-- /.container -->
</html>

zanhu01/templates/base01.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}zanhu01{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="a Q&A website">
    <meta name="author" content="__Sharon__">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endcompress %}
    {% endblock %}
    <!-- Le javascript
    ================================================== -->
    {# Placed at the top of the document so pages load faster with defer #}
    {% block javascript %}

      <!-- Bootstrap JS and its dependencies-->
      <script defer src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script defer src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script defer src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/popper.min.js' %}" type="text/javascript"></script>
      <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
      <!-- Your stuff: Third-party javascript libraries go here -->
      <script src="{% static 'js/jquery-ui.min.js' %}" type="text/javascript"></script>
      <!-- place project specific Javascript in this file -->
      <script type="text/javascript">
          const currentUser = "{{ request.user.username }}";
      </script>
      <script src="{% static 'js/reconnecting-websocket.js' %}" type="text/javascript"></script>
      <script src="{% static 'js/notifications.js' %}" type="text/javascript"></script>
      {% block js %}{% endblock js %}
      {% endcompress %}

    {% endblock javascript %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">zanhu01</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="#">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    {% block inline_javascript %}
    {# Script tags with only code, no src (defer by default) #}
    {% endblock inline_javascript %}
  </body>
</html>

zanhu01/templates/pages/about.html
{% extends "base.html" %}

zanhu01/templates/pages/home.html
{% extends "base.html" %}

zanhu01/templates/users/user_detail.html
{% extends "base.html" %}
{% load static thumbnail %}

{% block title %}{{ object.username }} - {{ block.super }}{% endblock %}

{% block css %}
    <link href="{% static 'css/user_profile.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
    <div class="row">
        <div class="col-md-2">
            {% thumbnail object.picture "x180" as im %}
                <img src="{{ im.url }}" alt="用户头像">
            {% empty %}
                <img src="{% static 'img/user.png' %}" height="180px" alt="没有头像"/>
            {% endthumbnail %}
        </div>

        <div class="col-md-7">
            <div class="card card-body"><p>{{ object.introduction }}</p></div>
        </div>
        <div class="col-md-3">
            <i class="fa fa-user-circle-o" aria-hidden="true"></i>
            {{ object.get_profile_name }}
            <br/>
            <i class="fa fa-envelope" aria-hidden="true"></i><a class="email" href="mailto:{{ object.email }}">   {{ object.email }}</a><br/>
            {% if object.job_title %}
                <i class="fa fa-briefcase" aria-hidden="true"></i>  {{ object.job_title }} <br/>
            {% endif %}
            {% if object.location %}
                <i class="fa fa-map-marker" aria-hidden="true"></i>  {{ object.location }} <br/>
            {% endif %}
            <div class="mb-2"></div>
            <!--自己的页面显示更新按钮-->
            {% if request.user.username == object.username %}
                <a class="btn btn-primary" href="{% url 'users:update' %}">更新信息</a>
            {% endif %}
        </div>
    </div>

    <div class="clear mb-3"></div>
    {% if object.personal_url %}
        <a href="{{ object.personal_url }}" style="font-size: 2em" title="个人网站"><i class="fa fa-link"></i> </a>
    {% endif %}
    {% if object.weibo %}
        <a href="{{ object.weibo }}" style="font-size: 2em" title="微博"><i class="fa fa-weibo"></i> </a>
    {% endif %}
    {% if object.zhihu %}
        <a href="{{ object.zhihu }}" style="font-size: 2em" title="知乎"><i class="fa fa-quora"></i> </a>
    {% endif %}
    {% if object.github %}
        <a href="{{ object.github }}" style="font-size: 2em" title="Github"><i class="fa fa-github"></i> </a>
    {% endif %}
    {% if object.linkedin %}
        <a href="{{ object.linkedin }}" style="font-size: 2em" title="LinkedIn"><i class="fa fa-linkedin"></i> </a>
    {% endif %}

    {% if request.user.username == object.username %}
        <!-- Data tiles -->
        <div class="row tile_count">
            <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
                <p class="fa fa-code"> 动态</p>
                <div class="count">{{ moments_num }}</div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
                <p class="fa fa-key"> 文章</p>
                <div class="count">{{ article_num }}</div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
                <p class="fa fa-comments"> 评论</p>
                <div class="count">{{ comment_num }}</div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
                <p class="fa fa-question-circle"> 提问</p>
                <div class="count">{{ question_num }}</div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
                <p class="fa fa-keyboard-o"> 回答</p>
                <div class="count">{{ answer_num }}</div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
                <p class="fa fa-navicon"> 互动</p>
                <div class="count">{{ interaction_num }}</div>
            </div>
        </div>
        <!-- /data tiles -->
    {% endif %}
{% endblock content %}

zanhu01/templates/users/user_form.html
{% extends "base.html" %}
{% load static crispy_forms_tags thumbnail %}

{% block title %}用户信息 - {{ block.super }}{% endblock %}

{% block css %}
    <link href="{% static 'css/user_form.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}

    <div class="row profile">
        <div class="col-md-3">
            <h2>{{ user.username }}</h2>
            {% if user.picture %}
                {% thumbnail user.picture "x180" as im %}
                    <img src="{{ im.url }}" alt="用户头像" id="pic">
                {% endthumbnail %}
            {% else %}
                <img src="{% static 'img/user.png' %}" alt="没有头像"/>
            {% endif %}
        </div>

        <div class="col-md-9">
            <form enctype="multipart/form-data" class="form-horizontal" method="post" action="{% url 'users:update' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="control-group">
                    <div class="controls">
                        <button type="submit" class="btn btn-primary">更新</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}